language: node_js
sudo: required

node_js:
  - '5'
  - '4'
  - '0.12'
  - '0.10'

before_install:
 - echo "deb http://www.rabbitmq.com/debian/ testing main"  | sudo tee  /etc/apt/sources.list.d/rabbitmq.list > /dev/null
 - sudo wget http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
 - sudo apt-key add rabbitmq-signing-key-public.asc
 - sudo apt-get update
 - sudo apt-get install rabbitmq-server -y
 - sudo service rabbitmq-server start
 - sudo rabbitmq-plugins enable rabbitmq_management
 - sudo service rabbitmq-server restart

after_script:
  npm run coverage
